// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLP3uCmEnZWaeI--YQwDvIEmkWaZI7Qfc',
    appId: '1:252143217416:web:e74a00e6ecad03b3921abd',
    messagingSenderId: '252143217416',
    projectId: 'healthy-cook-79dd3',
    authDomain: 'healthy-cook-79dd3.firebaseapp.com',
    storageBucket: 'healthy-cook-79dd3.appspot.com',
    measurementId: 'G-ZD2DZBDHD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUEo11TDOK-iqufKVzQ-IUrPhidEIvNgE',
    appId: '1:252143217416:android:4b119b582711b5e3921abd',
    messagingSenderId: '252143217416',
    projectId: 'healthy-cook-79dd3',
    storageBucket: 'healthy-cook-79dd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB42UQcHwrdtpkFxNnqle-Cy2_DE0BogSY',
    appId: '1:252143217416:ios:8f8ae2ecfccac164921abd',
    messagingSenderId: '252143217416',
    projectId: 'healthy-cook-79dd3',
    storageBucket: 'healthy-cook-79dd3.appspot.com',
    iosClientId:
        '252143217416-iph9plusmuov2rs4ou6vgkndoghld51a.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyCook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB42UQcHwrdtpkFxNnqle-Cy2_DE0BogSY',
    appId: '1:252143217416:ios:716f0d00b5faba6c921abd',
    messagingSenderId: '252143217416',
    projectId: 'healthy-cook-79dd3',
    storageBucket: 'healthy-cook-79dd3.appspot.com',
    iosClientId:
        '252143217416-gr3r70v4quisl36gb9ooddrhu0iarnr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyCook.RunnerTests',
  );
}
